"""
OPTIONAL / advanced path. The primary way to train the belt's classifier is
now entirely on-device, no laptop needed: SoundTrainingScreen.kt in the app
computes the same centroid this script computes (GoertzelFeatures.kt) and
sends it straight to the belt over BLE, which stores it in flash
(classifier_store.h/.cpp) -- no firmware reflash, no Python, no PC.

This script exists for cases the phone-only flow doesn't cover: bulk-
training from a larger curated dataset assembled elsewhere, or regenerating
a set of classes for a fresh board image. It writes a *compile-time* header
(src/classifier_model.h) -- that file no longer exists in the current
firmware build (classifier_interface.cpp now reads from the runtime
classifier_store instead), so as of this writing this script's output isn't
wired into anything; treat it as a reference implementation of the same
training math, not a working pipeline. Updating it to write directly into
the runtime store's format (or just push over BLE itself, PC-side) is
future work if this path turns out to be needed.

Usage:
    python tools/train_classifier.py path/to/sound_training_export.zip
    python tools/train_classifier.py path/to/extracted_folder/

Classical nearest-centroid classification (mean feature vector per class,
cosine similarity at inference), not a neural network -- deliberate, given
the realistic sample counts this produces (a handful of phone recordings per
class from the training screen, not thousands): a neural net "trained" on
that little data would be meaningless and would misrepresent what's actually
happening. Centroid matching is honest about what it is, explainable, and
works reasonably with small datasets, at near-zero on-device compute cost.
"""
import sys
import wave
import zipfile
import tempfile
import shutil
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).parent))
from goertzel import extract_features, TARGET_FREQS, BLOCK_SIZE, SAMPLE_RATE

MIN_SAMPLES_PER_CLASS = 3  # fewer than this isn't a class average, it's noise


def read_wav_samples(path: Path) -> np.ndarray:
    with wave.open(str(path), "rb") as wf:
        if wf.getframerate() != SAMPLE_RATE:
            raise ValueError(f"{path}: expected {SAMPLE_RATE}Hz, got {wf.getframerate()}")
        if wf.getsampwidth() != 2:
            raise ValueError(f"{path}: expected 16-bit PCM")
        if wf.getnchannels() != 1:
            raise ValueError(f"{path}: expected mono")
        raw = wf.readframes(wf.getnframes())
        return np.frombuffer(raw, dtype=np.int16).astype(np.float64)


def load_dataset(root: Path) -> dict:
    classes = {}
    for class_dir in sorted(p for p in root.iterdir() if p.is_dir()):
        wavs = sorted(class_dir.glob("*.wav"))
        if wavs:
            classes[class_dir.name] = wavs
    return classes


def compute_centroids(classes: dict) -> tuple:
    centroids = {}
    counts = {}
    for name, wavs in classes.items():
        feats = []
        for wav_path in wavs:
            try:
                samples = read_wav_samples(wav_path)
            except ValueError as e:
                print(f"  skipping {wav_path.name}: {e}")
                continue
            feats.append(extract_features(samples))
        if not feats:
            continue
        centroids[name] = np.mean(np.array(feats), axis=0)
        counts[name] = len(feats)
    return centroids, counts


def format_header(centroids: dict, counts: dict) -> str:
    usable = {k: v for k, v in centroids.items() if counts[k] >= MIN_SAMPLES_PER_CLASS}
    skipped = {k: counts[k] for k in centroids if k not in usable}

    lines = [
        "#pragma once",
        "// AUTO-GENERATED by tools/train_classifier.py -- do not hand-edit.",
        f"// Trained from {sum(counts.values())} total samples across {len(counts)} recorded classes;",
        f"// {len(usable)} classes had >= {MIN_SAMPLES_PER_CLASS} samples and are included below.",
    ]
    if skipped:
        skip_str = ", ".join(f"{k}({v})" for k, v in skipped.items())
        lines.append(f"// Skipped (too few samples for a reliable centroid): {skip_str}")
    lines += [
        "",
        f"#define CLASSIFIER_FEATURE_COUNT {len(TARGET_FREQS)}",
        f"#define CLASSIFIER_CLASS_COUNT {len(usable)}",
        f"#define CLASSIFIER_BLOCK_SIZE {BLOCK_SIZE}",
        "",
        "// Must match tools/goertzel.py's TARGET_FREQS exactly.",
        f"static const float CLASSIFIER_TARGET_FREQS[CLASSIFIER_FEATURE_COUNT] = "
        f"{{{', '.join(str(f) for f in TARGET_FREQS)}}};",
        "",
    ]

    if usable:
        names_str = ", ".join(f'"{k}"' for k in usable)
        lines.append(f"static const char* const CLASSIFIER_CLASS_NAMES[CLASSIFIER_CLASS_COUNT] = {{{names_str}}};")
        lines.append("static const float CLASSIFIER_CENTROIDS[CLASSIFIER_CLASS_COUNT][CLASSIFIER_FEATURE_COUNT] = {")
        for name, vec in usable.items():
            vals = ", ".join(f"{v:.6f}f" for v in vec)
            lines.append(f"    {{{vals}}}, // {name} ({counts[name]} samples)")
        lines.append("};")
    else:
        lines.append('static const char* const CLASSIFIER_CLASS_NAMES[1] = {"UNKNOWN"};   // unused, CLASSIFIER_CLASS_COUNT is 0')
        lines.append("static const float CLASSIFIER_CENTROIDS[1][CLASSIFIER_FEATURE_COUNT] = {{0}}; // unused, CLASSIFIER_CLASS_COUNT is 0")

    return "\n".join(lines) + "\n"


def main():
    if len(sys.argv) != 2:
        print("Usage: python train_classifier.py <sound_training_export.zip | folder>")
        sys.exit(1)

    src = Path(sys.argv[1])
    tmpdir = None
    try:
        if src.suffix == ".zip":
            tmpdir = tempfile.mkdtemp()
            with zipfile.ZipFile(src) as zf:
                zf.extractall(tmpdir)
            root = Path(tmpdir)
        else:
            root = src

        classes = load_dataset(root)
        if not classes:
            print(f"No class folders with .wav files found under {root}")
            sys.exit(1)

        print(f"Found {len(classes)} class(es): " + ", ".join(f"{k}({len(v)})" for k, v in classes.items()))
        centroids, counts = compute_centroids(classes)

        out_path = Path(__file__).parent.parent / "src" / "classifier_model.h"
        out_path.write_text(format_header(centroids, counts))

        usable_count = sum(1 for k in centroids if counts[k] >= MIN_SAMPLES_PER_CLASS)
        print(f"Wrote {out_path} -- {usable_count} usable class(es)")
    finally:
        if tmpdir:
            shutil.rmtree(tmpdir, ignore_errors=True)


if __name__ == "__main__":
    main()
